/*
 * articles.js - index of every article. Source of truth for the homepage,
 * search, filters, related articles, sitemap, RSS, and llms.txt.
 *
 * Each entry needs a matching hand-written page at articles/<slug>/index.html
 * (copy article-template.html). Run `node tools/build.js` after editing.
 *
 * type:       'tip' (short) or 'guide' (step by step)
 * problem:    'Fix it' | 'How to' | 'Hidden trick' | 'Gotcha' | 'Developer'
 * hubs:       'Marketing Hub' | 'Sales Hub' | 'Service Hub' | 'Content Hub' | 'Data Hub' | 'Commerce Hub' | 'Smart CRM'
 * draft:      true keeps it out of every list, sitemap, feed, and llms.txt
 */
var ARTICLES = [
  {
    slug: 'workflow-wont-re-enroll',
    title: "Contact won't re-enroll in a HubSpot workflow? Check these 6 things",
    excerpt: 'HubSpot enrolls a record once by default. Why re-enrollment fails, how to turn it on, and the triggers that can never re-enroll.',
    type: 'guide',
    problem: 'Fix it',
    hubs: ['Marketing Hub', 'Sales Hub', 'Service Hub', 'Data Hub'],
    features: ['Workflows'],
    tier: 'Professional or Enterprise',
    permissions: 'Super Admin or Workflows',
    verified: '2026-10-02',
    published: '2026-10-02',
    minutes: 10,
    difficulty: 'Intermediate',
    keywords: ['re-enroll', 'reenroll', 're-enrollment', 'enrollment trigger', 'workflow not triggering', 'automation']
  },
  {
    slug: 'duplicates-after-import',
    title: 'HubSpot import created duplicate contacts? Why it happens and how to fix it',
    excerpt: 'HubSpot only matches imported rows by a unique identifier. Spot an import that duplicated records, clean it up, and stop it next time.',
    type: 'guide',
    problem: 'Fix it',
    hubs: ['Smart CRM', 'Data Hub', 'Marketing Hub', 'Sales Hub'],
    features: ['Imports', 'Data quality'],
    tier: 'Any tier (merging needs Professional)',
    permissions: 'Import access; Data quality tools to merge',
    verified: '2026-10-02',
    published: '2026-10-02',
    minutes: 15,
    difficulty: 'Intermediate',
    keywords: ['duplicate', 'duplicates', 'dedupe', 'deduplicate', 'merge', 'import', 'record id', 'email', 'company domain'],
    related: ['find-hubspot-portal-id']
  },
  {
    slug: 'coded-template-missing-from-picker',
    title: 'Your coded HubSpot template is missing from the template picker? Look under Other',
    excerpt: 'The page template picker opens on your active theme. Templates that are not part of a theme only appear under Other.',
    type: 'tip',
    problem: 'Gotcha',
    hubs: ['Content Hub'],
    features: ['Pages', 'Design Manager'],
    tier: 'Any tier with pages',
    permissions: 'Website or landing page access',
    verified: '2026-10-02',
    published: '2026-10-02',
    minutes: 3,
    difficulty: 'Beginner',
    keywords: ['template', 'coded template', 'template picker', 'select a template', 'theme', 'design manager', 'hubl', 'landing page', 'extends']
  },
  {
    slug: 'find-hubspot-portal-id',
    title: 'How to find your HubSpot portal ID (Hub ID)',
    excerpt: 'Your portal ID, also called Hub ID or account ID, is in the account menu and in every HubSpot URL.',
    type: 'tip',
    problem: 'How to',
    hubs: ['Smart CRM'],
    features: ['Settings'],
    tier: 'All tiers, including free',
    permissions: 'Any user',
    verified: '2026-10-02',
    published: '2026-10-02',
    minutes: 1,
    difficulty: 'Beginner',
    keywords: ['portal id', 'hub id', 'account id', 'portalid', 'hubid', 'account number', 'url']
  },
  {
    slug: "never-opened-email-stat",
    title: "HubSpot says 180,000 contacts never opened your email? Check who was ever sent one",
    excerpt: "A HubSpot segment of contacts who never opened an email also includes everyone who was never sent one. How to build the honest version before you sunset anyone.",
    type: "tip",
    problem: "Gotcha",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Segments", "Workflows"],
    tier: "Marketing Hub Professional for the workflow; segments on paid tiers",
    permissions: "Segments and Workflows access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Intermediate",
    keywords: ["never opened", "unengaged", "email sunset", "open rate", "segment"],
  },
  {
    slug: "speed-to-lead-sla-workflow",
    title: "Build a speed-to-lead workflow in HubSpot with a follow-up SLA and escalation",
    excerpt: "A HubSpot workflow that creates a call task when a lead arrives, checks whether anyone made contact after a day, and escalates by email to the owner if nobody did.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Marketing Hub"],
    features: ["Workflows"],
    tier: "Professional or Enterprise",
    permissions: "Super Admin or Workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 20,
    difficulty: "Intermediate",
    keywords: ["speed to lead", "sla", "lead response", "task", "escalation"],
  },
  {
    slug: "sql-count-zero",
    title: "Your HubSpot report shows zero SQLs? Set lifecycle stage from the deal, not the contact",
    excerpt: "If reps work deals and never touch the contact's lifecycle stage, SQL reports stay at zero. A workflow can set associated contacts to Sales Qualified Lead when a deal reaches the right stage.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Sales Hub", "Marketing Hub"],
    features: ["Workflows", "Lifecycle stages"],
    tier: "Professional or Enterprise",
    permissions: "Super Admin or Workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Intermediate",
    keywords: ["sql", "sales qualified lead", "lifecycle stage", "report zero"],
  },
  {
    slug: "troubleshoot-enrollment",
    title: "Why didn't this record enroll? Use HubSpot's Troubleshoot enrollment tool",
    excerpt: "HubSpot workflows have a built-in tool that tests a specific record against the nine enrollment checks and tells you why it did or did not enroll.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Marketing Hub", "Sales Hub", "Service Hub", "Data Hub"],
    features: ["Workflows"],
    tier: "Professional or Enterprise",
    permissions: "Access to view the workflow",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Beginner",
    keywords: ["why not enrolled", "enrollment history", "workflow not triggering"],
  },
  {
    slug: "enrich-records-record-id-import",
    title: "Enrich HubSpot companies from a spreadsheet when names don't match: import by Record ID",
    excerpt: "When company names in a spreadsheet match more than one HubSpot company, export Record IDs, match your data to them, and import with Record ID as the identifier.",
    type: "guide",
    problem: "How to",
    hubs: ["Smart CRM", "Data Hub"],
    features: ["Imports", "Properties"],
    tier: "Any tier (property creation needs property settings access)",
    permissions: "Import access and Edit property settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 25,
    difficulty: "Intermediate",
    keywords: ["record id", "import update", "enrich", "naics"],
  },
  {
    slug: "bulk-assign-owners-from-sheet",
    title: "Bulk assign HubSpot company owners from a spreadsheet without overwriting anyone",
    excerpt: "Use a customer's own file of account owners to set Company owner on thousands of HubSpot companies, only where none is set, and handle owners who are not HubSpot users.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Smart CRM"],
    features: ["Imports", "Companies"],
    tier: "Any tier",
    permissions: "Import access; bulk edit access to companies",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 20,
    difficulty: "Intermediate",
    keywords: ["company owner", "assign owners", "bulk owner"],
  },
  {
    slug: "opt-out-contact-all-email",
    title: "How to opt a HubSpot contact out of all email (and why the API can't do it)",
    excerpt: "Actions, Opt out of email stops future marketing and one-to-one email from HubSpot. Where it lives, what it does not stop, and why scripts and the API cannot set it.",
    type: "tip",
    problem: "How to",
    hubs: ["Marketing Hub", "Sales Hub", "Smart CRM"],
    features: ["Contacts", "Email"],
    tier: "All tiers",
    permissions: "Marketing access permissions",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 4,
    difficulty: "Beginner",
    keywords: ["unsubscribe", "opt out", "gdpr", "do not email"],
  },
  {
    slug: "api-scripts-create-duplicates",
    title: "Your script created duplicate HubSpot records? Merge them, don't delete them",
    excerpt: "Why bulk writes through the HubSpot API create duplicate companies and contacts, how to merge instead of delete to keep associations, and how to write the script so it does not happen again.",
    type: "guide",
    problem: "Developer",
    hubs: ["Smart CRM"],
    features: ["API", "Duplicates"],
    tier: "Any tier with a private app",
    permissions: "Private app with CRM write scopes",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Advanced",
    keywords: ["api", "merge", "duplicates", "upsert"],
  },
  {
    slug: "template-doesnt-allow-modules",
    title: "'This template doesn't allow modules to be added' in HubSpot: three causes",
    excerpt: "A blank HubSpot page that will not let you add modules usually has a template problem: an empty drag and drop area, a broken extends path, or overlapping columns.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Content Hub"],
    features: ["Pages", "Design Manager"],
    tier: "Any tier with website or landing pages",
    permissions: "Design Manager and page access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Advanced",
    keywords: ["dnd_area", "template", "editor error", "modules"],
  },
  {
    slug: "clone-landing-page-per-location",
    title: "Clone a HubSpot landing page for each location: what to change every time",
    excerpt: "How to clone one good HubSpot landing page for each community or location, and the four settings plus content to change on every clone.",
    type: "guide",
    problem: "How to",
    hubs: ["Content Hub"],
    features: ["Pages"],
    tier: "Any tier with website or landing pages",
    permissions: "Create and edit pages",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Beginner",
    keywords: ["clone page", "landing page", "location pages"],
  },
  {
    slug: "starter-page-limit",
    title: "'You have reached your page limit' in HubSpot: look at your drafts",
    excerpt: "HubSpot's Starter tier limits how many landing pages you can create. Untitled drafts show up in the same list as live pages, so check them first.",
    type: "tip",
    problem: "Gotcha",
    hubs: ["Content Hub"],
    features: ["Pages"],
    tier: "Starter tier",
    permissions: "Page access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 4,
    difficulty: "Beginner",
    keywords: ["page limit", "starter", "untitled drafts"],
  },
  {
    slug: "offline-sources-explained",
    title: "HubSpot 'Offline Sources' is not offline: how to see what created those contacts",
    excerpt: "Offline Sources in HubSpot means a record was created outside tracked web traffic, such as an import, the API, a connected app, or by hand. How to break it apart with the drill-down properties.",
    type: "guide",
    problem: "Hidden trick",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Properties", "Attribution"],
    tier: "All tiers for the properties; reports need Professional",
    permissions: "Any user who can view contacts",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 12,
    difficulty: "Intermediate",
    keywords: ["offline sources", "original source", "attribution", "drill-down"],
  },
  {
    slug: "campaign-zero-sessions",
    title: "HubSpot campaign shows lots of influenced contacts but 0 sessions? You need tracking URLs",
    excerpt: "A HubSpot campaign full of assets can show hundreds of influenced contacts and zero sessions. Sessions only count when visits arrive through the campaign's tracking URL.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Marketing Hub"],
    features: ["Campaigns"],
    tier: "Marketing Hub Professional or Enterprise",
    permissions: "Campaigns access and Tracking URLs access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Intermediate",
    keywords: ["campaign sessions", "utm", "tracking url", "influenced contacts"],
  },
  {
    slug: "which-reports-hubspot-can-build",
    title: "Which reports can HubSpot build? Report types, limits, and what needs a higher tier",
    excerpt: "HubSpot's custom report types: single object, funnel, custom report builder, attribution, and email reports. What each can and cannot do, and which tier you need.",
    type: "guide",
    problem: "How to",
    hubs: ["Smart CRM", "Marketing Hub", "Sales Hub"],
    features: ["Reports"],
    tier: "Custom reports need Professional or Enterprise",
    permissions: "Create and own, and Edit reports",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Beginner",
    keywords: ["custom report", "report builder", "report types", "funnel"],
  },
  {
    slug: "hubsql-beta-api",
    title: "HubSQL beta: what it is, what it is not, and the 403 MISSING_SCOPES fix",
    excerpt: "HubSpot's HubSQL beta lets you run SQL against CRM data over an API. What it can do, why it cannot connect to your SQL server, and how to fix a 403 for missing scopes.",
    type: "tip",
    problem: "Developer",
    hubs: ["Smart CRM"],
    features: ["API"],
    tier: "Private beta (invite only at the time of writing)",
    permissions: "Private or legacy app with the required read scopes",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Advanced",
    keywords: ["hubsql", "sql", "api", "403", "missing scopes"],
  },
  {
    slug: "speed-up-landing-page",
    title: "Speed up a HubSpot landing page: measure first, then fix images and page-level code",
    excerpt: "How to find out why a HubSpot landing page is slow with Lighthouse, then fix the usual causes: heavy images, layout shift, and extra scripts in the page's Head and Footer HTML.",
    type: "guide",
    problem: "How to",
    hubs: ["Content Hub"],
    features: ["Pages", "Performance"],
    tier: "Any tier with landing or website pages",
    permissions: "Edit pages",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Intermediate",
    keywords: ["page speed", "lighthouse", "core web vitals", "head html"],
  },
  {
    slug: "default-lifecycle-and-deal-stages",
    title: "HubSpot's default lifecycle stages, lead statuses, and deal stages (with internal names)",
    excerpt: "The out-of-the-box HubSpot lifecycle stages, lead statuses, and default Sales Pipeline deal stages, with the internal values you need for imports, workflows, and APIs.",
    type: "tip",
    problem: "How to",
    hubs: ["Smart CRM", "Sales Hub"],
    features: ["Properties", "Deals"],
    tier: "All tiers (editing stages needs Professional for some objects)",
    permissions: "Any user can view; Edit property settings to change",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["lifecycle stages", "lead status", "deal stages", "internal names", "default pipeline"]
  },
  {
    slug: "lifecycle-date-properties",
    title: "Stop creating custom timestamp fields: HubSpot already tracks when a record entered each lifecycle stage",
    excerpt: "HubSpot automatically creates date entered and time in stage properties for every lifecycle stage. Check them before you build custom date fields for a journey or funnel.",
    type: "tip",
    problem: "Hidden trick",
    hubs: ["Smart CRM", "Marketing Hub", "Sales Hub"],
    features: ["Properties", "Lifecycle stages"],
    tier: "All tiers for the properties; reports and workflows depend on your tier",
    permissions: "Any user can view; reports need report access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Intermediate",
    keywords: ["date entered", "time in stage", "lifecycle timestamps", "became a"]
  },
  {
    slug: "detect-hubspot-tracking-code",
    title: "How to tell if a website uses HubSpot: check for the tracking code",
    excerpt: "HubSpot's tracking code is a script from js.hs-scripts.com with the account's Hub ID. How to check one site by hand, validate your own, and scan a list of domains.",
    type: "guide",
    problem: "How to",
    hubs: ["Smart CRM", "Marketing Hub"],
    features: ["Tracking code"],
    tier: "All tiers",
    permissions: "Settings access to see your own tracking code",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 12,
    difficulty: "Intermediate",
    keywords: ["tracking code", "hs-scripts", "hub id", "uses hubspot", "validate"]
  },
  {
    slug: "close-stale-deals",
    title: "How to close out stale HubSpot deals safely: check activity first, then use a reason",
    excerpt: "A safe routine for closing old HubSpot deals: find stale ones on the board, check last activity and next steps, then move them to Closed Lost with a reason.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub"],
    features: ["Deals"],
    tier: "All tiers (bulk edit and reports vary)",
    permissions: "Edit access to deals",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Beginner",
    keywords: ["stale deals", "closed lost", "pipeline cleanup", "last activity"]
  },
  {
    slug: "duplicate-companies-from-connector-ids",
    title: "Two HubSpot companies share one connector ID? Merge the safe ones and hold the collisions",
    excerpt: "When a sync connector keys on an external ID and two HubSpot companies carry it, data splits across both. How to triage the groups, merge the safe ones, and leave genuine ID collisions alone.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Smart CRM", "Data Hub"],
    features: ["Duplicates", "Integrations"],
    tier: "Any tier (bulk merge tooling varies; API merge needs a private app)",
    permissions: "Super Admin or merge access to companies",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 30,
    difficulty: "Advanced",
    keywords: ["connectwise", "duplicate companies", "merge", "connector id", "sync"]
  },
  {
    slug: "callrail-duplicate-contacts",
    title: "Call tracking is creating duplicate HubSpot contacts? Fix the source before you merge",
    excerpt: "Placeholder emails from a call tracking tool stop texts and calls matching real HubSpot contacts and create duplicates. How to analyze the duplicates by phone, what is safe to merge, and how to stop it.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Smart CRM", "Marketing Hub"],
    features: ["Duplicates", "Integrations"],
    tier: "Any tier (workflow-based dedupe needs Data Hub Professional)",
    permissions: "Merge access to contacts; settings access in the call tracking tool",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 25,
    difficulty: "Advanced",
    keywords: ["callrail", "duplicate contacts", "placeholder email", "texting", "call tracking"]
  },
  {
    slug: "theme-upload-validation-errors",
    title: "Seven HubSpot theme upload errors I hit, and how to sweep for the whole class",
    excerpt: "Building a HubSpot theme from scratch failed validation six times. The seven errors: reserved field names, template type suffixes, global field IDs, unsupported field types, and breakpoint names.",
    type: "guide",
    problem: "Developer",
    hubs: ["Content Hub"],
    features: ["Design Manager", "Themes"],
    tier: "Any account with CMS or Content Hub access",
    permissions: "Developer access and CLI access to the account",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Advanced",
    keywords: ["theme upload", "validation", "fields.json", "reserved field name", "hs cms upload"]
  },
  {
    slug: "exclude-own-traffic",
    title: "Exclude your own visits from HubSpot analytics (and the catch with form tests)",
    excerpt: "How to keep your own traffic out of HubSpot analytics with an IP filter and referrer filter, what bot filtering does, and what happens to your own test form submissions.",
    type: "tip",
    problem: "How to",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Tracking code", "Analytics"],
    tier: "All tiers",
    permissions: "Account access to Tracking & Analytics settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["exclude traffic", "internal traffic", "ip filter", "analytics"]
  },
  {
    slug: "teams-phone-recordings-to-hubspot",
    title: "Can HubSpot get Microsoft Teams Phone recordings and transcripts? What works and what doesn't",
    excerpt: "HubSpot logs Teams calls and syncs Teams meeting recordings, but not Teams Phone recordings. What Microsoft Graph offers, the 2026 transcript setting, HubSpot's transcripts API, and a Make versus Data Hub comparison.",
    type: "guide",
    problem: "Developer",
    hubs: ["Sales Hub", "Data Hub"],
    features: ["Integrations", "Calling"],
    tier: "See the HubSpot Teams app page for requirements; the custom pipeline needs a public app",
    permissions: "HubSpot Super Admin; Microsoft 365 admin",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Advanced",
    keywords: ["microsoft teams", "teams phone", "call transcripts", "recordings", "microsoft graph"]
  },
  {
    slug: "hubspot-object-type-ids",
    title: "HubSpot object type IDs (0-1, 0-47, 0-48) and how to use them in links and the API",
    excerpt: "The numeric object type IDs behind HubSpot URLs and API calls: contacts 0-1, companies 0-2, deals 0-3, meetings 0-47, calls 0-48 and more, with a fix for links that land on a blank page.",
    type: "tip",
    problem: "Hidden trick",
    hubs: ["Smart CRM"],
    features: ["API", "Links"],
    tier: "All tiers",
    permissions: "Any user",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Intermediate",
    keywords: ["object type id", "0-47", "0-48", "objecttypeid", "meeting link", "blank page"]
  },
  {
    slug: "revenue-attribution-deal-requirements",
    title: "Deal missing from HubSpot revenue attribution? A deal needs four things",
    excerpt: "HubSpot's revenue attribution reports only include closed won deals with an associated contact, known amount, create date and close date, and recorded interactions. A checklist for why a deal is missing.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Marketing Hub", "Sales Hub"],
    features: ["Attribution", "Campaigns"],
    tier: "Revenue attribution reports need Marketing Hub Enterprise",
    permissions: "Report access; edit access to deals to fix records",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Intermediate",
    keywords: ["revenue attribution", "campaign revenue", "closed won", "deal missing"]
  },
  {
    slug: "spreadsheet-board-to-hubspot-pipelines",
    title: "Move a project board (Planner, Trello, a spreadsheet) into HubSpot pipelines",
    excerpt: "How to turn an exported task board into HubSpot pipelines, deals, companies, contacts, and notes: map each field, do a dry run, approve each piece, and verify counts.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Smart CRM"],
    features: ["Pipelines", "Imports"],
    tier: "The number of pipelines depends on your subscription",
    permissions: "Super Admin or access to create pipelines and properties",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 40,
    difficulty: "Advanced",
    keywords: ["planner", "trello", "board import", "pipelines", "migrate"]
  },
  {
    slug: "form-submissions-marked-spam",
    title: "HubSpot form submissions marked as spam? Check for an unregistered site domain",
    excerpt: "Forms embedded on a website HubSpot does not recognize get their submissions flagged as spam. How to spot the warning, register the domain, and release the submissions.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Forms", "Tracking code"],
    tier: "All tiers",
    permissions: "Edit forms; account access to Tracking & Analytics settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Beginner",
    keywords: ["form spam", "unregistered domain", "submissions missing", "release to submissions"]
  },
  {
    slug: "embed-hubspot-form-external-site",
    title: "How to embed a HubSpot form on a site that is not hosted in HubSpot",
    excerpt: "Where to find a HubSpot form's embed code and share link, what to paste into your page, and the two things that must be true for it to work: the tracking code and a registered domain.",
    type: "guide",
    problem: "How to",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Forms"],
    tier: "All tiers for the standard embed; developer code needs Professional",
    permissions: "Edit forms",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Intermediate",
    keywords: ["embed form", "external site", "hbspt.forms.create", "share link"]
  },
  {
    slug: "connect-custom-domain-to-hubspot",
    title: "Connect your own domain to HubSpot (and what the brand domain limit means)",
    excerpt: "How to see your connected HubSpot hosting domains, what a brand domain is, the DNS record each type needs, and how SSL is turned on. Includes the one brand domain limit on a lower tier.",
    type: "guide",
    problem: "How to",
    hubs: ["Content Hub"],
    features: ["Domains", "Pages"],
    tier: "Content Hub; the number of brand domains depends on your tier",
    permissions: "Super Admin or domain settings access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Intermediate",
    keywords: ["custom domain", "cname", "brand domain", "ssl"]
  },
  {
    slug: "active-vs-static-segments",
    title: "Active vs static segments in HubSpot: which one to build",
    excerpt: "Active segments update themselves as records meet or stop meeting your criteria. Static segments are a fixed snapshot. When each is the right choice, with the Type column to check what you have.",
    type: "tip",
    problem: "How to",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Segments"],
    tier: "All paid tiers",
    permissions: "Segments access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["active list", "static list", "segments", "smart list"]
  },
  {
    slug: "hubspot-meetings-link",
    title: "Set up a HubSpot meetings link so people can book time with you",
    excerpt: "Create a HubSpot scheduling page, connect your calendar so availability is accurate, and share the link on your website and in email. What the setup screen looks like and what to configure.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Smart CRM"],
    features: ["Meetings"],
    tier: "See HubSpot's meetings tool documentation for what your tier includes",
    permissions: "Meetings access and a connected calendar",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Beginner",
    keywords: ["meetings link", "scheduling page", "calendly alternative", "booking link"]
  },
  {
    slug: "form-consent-checkbox",
    title: "Add a consent checkbox to a HubSpot form (newsletter signup example)",
    excerpt: "How a HubSpot form can ask for consent: a required checkbox for the communication type plus a processing notice. The three consent options and the setup used on a real newsletter form.",
    type: "tip",
    problem: "How to",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Forms", "Consent"],
    tier: "All tiers",
    permissions: "Edit forms; settings access for privacy options",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Beginner",
    keywords: ["consent checkbox", "gdpr form", "legitimate interest", "newsletter signup"]
  },
  {
    slug: "workflow-settings-explained",
    title: "HubSpot workflow settings explained: schedules, pauses, notifications, and unenrolling from other workflows",
    excerpt: "A walk through the Settings panel of a HubSpot workflow: when actions can run, pausing on dates, auto turn-off, performance alerts, conversion metrics, and the setting that unenrolls records from other workflows.",
    type: "guide",
    problem: "How to",
    hubs: ["Marketing Hub", "Sales Hub", "Service Hub"],
    features: ["Workflows"],
    tier: "Professional or Enterprise (performance notifications are Enterprise)",
    permissions: "Super Admin or Workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Intermediate",
    keywords: ["workflow settings", "pause actions", "turn off automatically", "unenroll from other workflows"]
  },
  {
    slug: "workflow-delay-and-branch-actions",
    title: "Delay and if/then branch actions in HubSpot workflows: what to set",
    excerpt: "How the Delay action and an if/then branch are configured in a HubSpot workflow: set amount of time, business days only, and a branch based on a property such as Last contacted.",
    type: "guide",
    problem: "How to",
    hubs: ["Marketing Hub", "Sales Hub", "Service Hub"],
    features: ["Workflows"],
    tier: "Professional or Enterprise",
    permissions: "Super Admin or Workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Beginner",
    keywords: ["workflow delay", "business days", "if/then branch", "list branch"]
  },
  {
    slug: "workflow-create-task-action",
    title: "The Create task action in a HubSpot workflow: title, type, due date, and reminder",
    excerpt: "How to configure the Create task action in a HubSpot workflow: a title with personalization tokens, a task type, a due date, and an email reminder, with a call-task example.",
    type: "tip",
    problem: "How to",
    hubs: ["Sales Hub", "Marketing Hub", "Service Hub"],
    features: ["Workflows", "Tasks"],
    tier: "Professional or Enterprise",
    permissions: "Super Admin or Workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Beginner",
    keywords: ["create task", "workflow task", "call task", "task due date"]
  },
  {
    slug: "workflow-edit-record-action",
    title: "The Edit record action in HubSpot workflows: replace, append, clear, and copy values",
    excerpt: "How the Edit record action works in a HubSpot workflow: choose the record, the property, the change type, and the value, including copying from another property and editing associated records.",
    type: "guide",
    problem: "How to",
    hubs: ["Marketing Hub", "Sales Hub", "Service Hub"],
    features: ["Workflows", "Properties"],
    tier: "Professional or Enterprise",
    permissions: "Super Admin or Workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Beginner",
    keywords: ["edit record", "set property value", "change type", "append", "copy property"]
  },
  {
    slug: "workflow-enrollment-triggers-explained",
    title: "HubSpot workflow enrollment triggers: event-based vs filter criteria",
    excerpt: "The two parts of a HubSpot workflow trigger: the event that starts enrollment and the conditions a record must meet. How they combine, what manual enrollment skips, and a common event trigger limitation.",
    type: "guide",
    problem: "How to",
    hubs: ["Marketing Hub", "Sales Hub", "Service Hub"],
    features: ["Workflows"],
    tier: "Professional or Enterprise",
    permissions: "Super Admin or Workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Intermediate",
    keywords: ["enrollment trigger", "event based", "filter criteria", "manual enrollment"]
  },
  {
    slug: "workflows-health-unused-and-issues",
    title: "Find unused HubSpot workflows and workflows with issues: the Health tab",
    excerpt: "Where HubSpot shows how many workflows are unused or have issues: the Health tab on the Automation page, the Unused view, and the Review automation issues tool.",
    type: "tip",
    problem: "Hidden trick",
    hubs: ["Marketing Hub", "Sales Hub", "Service Hub"],
    features: ["Workflows"],
    tier: "Professional or Enterprise",
    permissions: "Access to workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["unused workflows", "automation issues", "workflow health", "cleanup"]
  },
  {
    slug: "dashboard-settings-access-refresh-caching",
    title: "HubSpot dashboard settings: who can see it, how often it refreshes, and caching",
    excerpt: "What each setting in a HubSpot dashboard's settings panel does: owner, access level, default dashboard, automatic refresh, color theme, and the dashboard cache setting.",
    type: "guide",
    problem: "How to",
    hubs: ["Smart CRM", "Marketing Hub", "Sales Hub"],
    features: ["Dashboards"],
    tier: "All paid tiers; specific user and team access needs Enterprise",
    permissions: "Dashboard owner, or Super Admin",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 7,
    difficulty: "Beginner",
    keywords: ["dashboard settings", "dashboard access", "report caching", "default dashboard", "refresh"]
  },
  {
    slug: "add-reports-to-a-dashboard",
    title: "Add reports to a HubSpot dashboard: My reports, ready-made reports, and the permission catch",
    excerpt: "How the Add reports panel works in a HubSpot dashboard: My reports and Ready-made reports tabs, search and filters, drag or Add, and why the panel can say you do not have permission.",
    type: "tip",
    problem: "How to",
    hubs: ["Smart CRM", "Marketing Hub", "Sales Hub"],
    features: ["Dashboards", "Reports"],
    tier: "All paid tiers; custom reports need Professional",
    permissions: "Edit access to the dashboard",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["add reports", "dashboard", "ready-made reports", "permission to edit dashboard"]
  },
  {
    slug: "email-tracking-consent-review",
    title: "HubSpot says 'Before you send: review your email tracking settings'. What it means and what to do",
    excerpt: "The HubSpot warning about email open and click tracking consent: where it appears, the Tracking settings it links to, and how to turn tracking off account-wide or for one email.",
    type: "tip",
    problem: "Gotcha",
    hubs: ["Marketing Hub"],
    features: ["Email", "Consent"],
    tier: "All tiers with marketing email",
    permissions: "Account access to email settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Beginner",
    keywords: ["email tracking", "open tracking", "click tracking", "gdpr", "consent"]
  },
  {
    slug: "double-opt-in-marketing-email",
    title: "Double opt-in for HubSpot marketing email: what it does and what it limits",
    excerpt: "How HubSpot double opt-in works: a confirmation email after a form submission, who counts as confirmed, the difference between basic and advanced setup, and the limits to know before you turn it on.",
    type: "guide",
    problem: "How to",
    hubs: ["Marketing Hub"],
    features: ["Email", "Consent"],
    tier: "Basic double opt-in on Starter and free tools; per-form control and custom confirmation email need Professional or Enterprise",
    permissions: "Account access to email settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Intermediate",
    keywords: ["double opt-in", "confirmation email", "email consent", "doi"]
  },
  {
    slug: "email-subscription-types",
    title: "HubSpot email subscription types: marketing, one-to-one, customer service, and your own",
    excerpt: "How HubSpot subscription types work: the default types, the subscription preferences page contacts see, how to create or archive types, and what happens to the one-to-one type.",
    type: "guide",
    problem: "How to",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Email", "Subscriptions"],
    tier: "Marketing Hub Starter and up; Content Hub Professional and Enterprise",
    permissions: "Account access to email settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Beginner",
    keywords: ["subscription types", "preferences page", "unsubscribe", "one to one"]
  },
  {
    slug: "hubspot-properties-page-tour",
    title: "The HubSpot Properties page: find, filter, and audit your properties",
    excerpt: "A tour of the Properties settings page in HubSpot: choosing an object, the Properties, Conditional logic, Groups, and Archived tabs, the filters, search, and exporting a list of properties.",
    type: "tip",
    problem: "How to",
    hubs: ["Smart CRM"],
    features: ["Properties"],
    tier: "All tiers",
    permissions: "Edit property settings to create or edit; view access to browse",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Beginner",
    keywords: ["properties", "property settings", "custom properties", "property groups", "export properties"]
  },
  {
    slug: "conditional-property-logic",
    title: "Conditional property logic in HubSpot: show or require a field based on another",
    excerpt: "How HubSpot conditional property logic works: where to create it, which property types can drive it, where it is enforced, and the gap that workflows and other tools leave open.",
    type: "tip",
    problem: "How to",
    hubs: ["Smart CRM", "Sales Hub"],
    features: ["Properties"],
    tier: "Professional or Enterprise",
    permissions: "Edit property settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Intermediate",
    keywords: ["conditional property logic", "dependent fields", "required fields", "properties"]
  },
  {
    slug: "check-property-usage-before-deleting",
    title: "Check where a HubSpot property is used before you change or delete it",
    excerpt: "Use the property editor's Usage section to see a property's fill rate and every view, form, workflow, and card that uses it, before you rename, change, or archive it.",
    type: "tip",
    problem: "Hidden trick",
    hubs: ["Smart CRM"],
    features: ["Properties"],
    tier: "All tiers",
    permissions: "View access to property settings; Edit property settings to change",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["property usage", "delete property", "archive property", "fill rate", "property editor"]
  },
  {
    slug: "dropdown-option-labels-vs-internal-names",
    title: "HubSpot dropdown options: labels vs internal names, and why imports and integrations care",
    excerpt: "Every option in a HubSpot dropdown, radio, or checkbox property has a label and an internal name. Where to see both, how imports match them, and the other columns on the options table.",
    type: "tip",
    problem: "Gotcha",
    hubs: ["Smart CRM"],
    features: ["Properties", "Import"],
    tier: "All tiers",
    permissions: "View access to property settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Intermediate",
    keywords: ["dropdown options", "internal value", "internal name", "import values", "enumeration property"]
  },
  {
    slug: "hubspot-saved-views-and-filters",
    title: "HubSpot saved views: quick filters, advanced filters, view types, and sharing",
    excerpt: "How saved views work on HubSpot index pages such as Contacts: view tabs, quick and advanced filters, the View settings panel with table, board, calendar, Gantt and report views, and sharing.",
    type: "guide",
    problem: "How to",
    hubs: ["Smart CRM"],
    features: ["Views", "Records"],
    tier: "All tiers",
    permissions: "Access to the object",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Beginner",
    keywords: ["saved views", "filters", "index page", "board view", "share view"]
  },
  {
    slug: "find-records-from-an-import",
    title: "Find the records from a HubSpot import, and what else the import page can do",
    excerpt: "Where HubSpot keeps import history, what the import details page shows, and the Actions menu that lets you view the imported records, add them to a segment, or download the file.",
    type: "tip",
    problem: "Hidden trick",
    hubs: ["Smart CRM"],
    features: ["Import", "Segments"],
    tier: "All tiers",
    permissions: "Import access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["import history", "imported contacts", "segment from import", "import errors"]
  },
  {
    slug: "deal-default-amount-and-close-date",
    title: "HubSpot deal settings: default deal amount, default close date, and the create form",
    excerpt: "The Deals setup page in HubSpot: choosing how the deal amount is calculated (TCV, ACV, ARR, MRR, or manual), the default close date for new deals, the create deal form, and line item owner sync.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Smart CRM"],
    features: ["Deals"],
    tier: "All tiers",
    permissions: "Account settings access; Super Admin to set a default deal name",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Intermediate",
    keywords: ["deal amount", "acv", "tcv", "arr", "mrr", "default close date", "deal settings"]
  },
  {
    slug: "deal-pipeline-rules",
    title: "HubSpot pipeline rules: stop deals skipping stages or moving backwards",
    excerpt: "The Pipeline Rules tab in HubSpot deal pipeline settings: limit creation to certain stages, restrict skipping and moving backwards, control editing access, and approvals, plus who can bypass them.",
    type: "tip",
    problem: "How to",
    hubs: ["Sales Hub"],
    features: ["Pipelines", "Deals"],
    tier: "Professional or Enterprise; deal approvals need Sales Hub Enterprise",
    permissions: "Super Admin or Edit property settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Intermediate",
    keywords: ["pipeline rules", "skip stages", "deal stage", "deal approval", "pipeline governance"]
  },
  {
    slug: "deal-stage-probability",
    title: "HubSpot deal stage probability: what the percentage does and where to change it",
    excerpt: "Every HubSpot deal stage has a probability. Where to see and change it in pipeline settings, HubSpot's default stages and percentages, and how it drives the weighted amount on the board.",
    type: "tip",
    problem: "How to",
    hubs: ["Sales Hub"],
    features: ["Pipelines", "Deals"],
    tier: "All tiers",
    permissions: "Edit property settings or Super Admin to change stages",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["deal probability", "weighted amount", "deal stages", "pipeline settings", "forecast"]
  },
  {
    slug: "find-pipeline-and-stage-ids",
    title: "Find a HubSpot pipeline ID and deal stage IDs (and how many pipelines you can have)",
    excerpt: "Where to find the internal IDs for HubSpot deal pipelines and stages, which imports, workflows, integrations, and the API need, plus the pipeline count and limit shown in settings.",
    type: "tip",
    problem: "Developer",
    hubs: ["Sales Hub", "Smart CRM"],
    features: ["Pipelines", "API"],
    tier: "All tiers; custom pipeline limits depend on subscription",
    permissions: "Access to pipeline settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Intermediate",
    keywords: ["stage id", "pipeline id", "dealstage", "internal name", "pipeline limit"]
  },
  {
    slug: "hubspot-deal-tags",
    title: "HubSpot deal tags: color-coded labels for Overdue, Stale, and anything you can filter",
    excerpt: "How HubSpot deal tags (object tags) work: where to set them per pipeline, the conditions behind them, the tags in my demo pipeline, tier differences, and where else the tag property can be used.",
    type: "tip",
    problem: "How to",
    hubs: ["Sales Hub"],
    features: ["Pipelines", "Deals"],
    tier: "Starter (tags for all pipelines); Professional or Enterprise (tags per pipeline)",
    permissions: "Super Admin",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Beginner",
    keywords: ["deal tags", "object tags", "deal board", "stale deals", "overdue deals"]
  },
  {
    slug: "deal-close-date-changes-when-won",
    title: "Why HubSpot changes a deal's close date when you mark it won or lost",
    excerpt: "HubSpot sets a deal's close date to today when the deal moves to a closed stage. Where that templated automation lives, the second rule for reopened deals, and when to turn either off.",
    type: "tip",
    problem: "Gotcha",
    hubs: ["Sales Hub"],
    features: ["Pipelines", "Deals"],
    tier: "All tiers",
    permissions: "Access to pipeline settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["close date", "deal closed won", "close date automation", "pipeline automate"]
  },
  {
    slug: "hubspot-snippets-shortcuts",
    title: "HubSpot snippets: reusable text you insert with a # shortcut",
    excerpt: "How HubSpot snippets work: where to create them, the # shortcut, where you can use them, the 2,500 character limit, personalization tokens, and the account limits by tier.",
    type: "tip",
    problem: "Hidden trick",
    hubs: ["Sales Hub", "Service Hub"],
    features: ["Snippets"],
    tier: "Free (3 snippets); Starter, Professional, Enterprise (5,000 per account)",
    permissions: "Sales access to edit or delete snippets",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["snippets", "shortcut", "reusable text", "sales tools", "personalization tokens"]
  },
  {
    slug: "sales-email-templates",
    title: "HubSpot sales email templates: create, share, personalize, and track them",
    excerpt: "How HubSpot message templates for one-to-one email work: the templates list, sharing and folders, personalization tokens, previewing with a contact, the limits by tier, and reporting with the Template ID property.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Service Hub"],
    features: ["Templates", "Email"],
    tier: "Free (3 templates on new accounts); paid Sales Hub or Service Hub for more",
    permissions: "Sales or Service access; Core seat on Starter beyond the default limit",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 7,
    difficulty: "Beginner",
    keywords: ["email templates", "sales templates", "message templates", "personalization tokens", "template id"]
  },
  {
    slug: "attribution-interaction-types",
    title: "HubSpot attribution interaction types: which touches count, and which are off by default",
    excerpt: "The attribution settings page in HubSpot: which interaction types are included in revenue and deal create attribution reports, which are off by default, and the reprocessing that follows a change.",
    type: "tip",
    problem: "Gotcha",
    hubs: ["Marketing Hub"],
    features: ["Attribution", "Reports"],
    tier: "Marketing Hub Enterprise",
    permissions: "Account settings access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Intermediate",
    keywords: ["attribution", "interaction types", "revenue attribution", "deal create attribution"]
  },
  {
    slug: "account-defaults-time-zone-fiscal-year",
    title: "HubSpot account defaults: time zone and fiscal year, and what they change",
    excerpt: "The Account Defaults page in HubSpot: account name, time zone, and fiscal year, what each one affects across scheduling, workflows, and reports, and the user time zone that is separate.",
    type: "tip",
    problem: "How to",
    hubs: ["Smart CRM"],
    features: ["Account settings"],
    tier: "All tiers",
    permissions: "Account Access or Super Admin",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["account defaults", "time zone", "fiscal year", "account settings"]
  },
  {
    slug: "hubspot-multiple-currencies",
    title: "Multiple currencies in HubSpot: company currency, exchange rates, and how deals convert",
    excerpt: "How HubSpot handles more than one currency: the company currency, adding currencies, automatic exchange rate updates, and how the Amount in company currency is calculated for open and closed deals.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Smart CRM"],
    features: ["Currency", "Deals"],
    tier: "Company currency on all tiers; extra currencies need Starter, Professional, or Enterprise",
    permissions: "Super Admin or Edit account defaults to view; billing permissions to add currencies",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Intermediate",
    keywords: ["multiple currencies", "exchange rate", "company currency", "amount in company currency"]
  },
  {
    slug: "hubspot-notification-preferences",
    title: "HubSpot notification settings: pop-up, browser, bell, email, mobile, and Slack",
    excerpt: "How HubSpot user notifications work: the six channels, setting channel defaults, turning topics on or off, the daily email notification cap, and notification profiles admins can push to users.",
    type: "tip",
    problem: "How to",
    hubs: ["Smart CRM"],
    features: ["Notifications"],
    tier: "All tiers; notification profiles need Professional or Enterprise",
    permissions: "Any user (own notifications); Super Admin for notification profiles",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["notifications", "notification settings", "email notifications", "slack notifications", "bell"]
  },
  {
    slug: "connect-inbox-alias-signature",
    title: "Your HubSpot email setup: connect your inbox, add an alias, and set a signature",
    excerpt: "The personal Email preferences tab in HubSpot: connecting a work inbox, adding an email alias, and managing email signatures, with what each one is for.",
    type: "tip",
    problem: "How to",
    hubs: ["Sales Hub", "Smart CRM"],
    features: ["Email", "User settings"],
    tier: "All tiers",
    permissions: "Personal email access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Beginner",
    keywords: ["connect inbox", "email alias", "email signature", "connected email", "personal email"]
  },
  {
    slug: "contact-owner-changed-automatically",
    title: "Why a HubSpot contact's owner changed when you emailed them",
    excerpt: "HubSpot can assign an unowned contact to whoever emails them from the CRM, and give contacts their company's owner. Where those two settings live and when to turn them off.",
    type: "tip",
    problem: "Gotcha",
    hubs: ["Smart CRM", "Sales Hub"],
    features: ["Ownership", "Contacts"],
    tier: "All tiers",
    permissions: "Account settings access to change",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["contact owner", "owner changed", "unowned contacts", "company owner", "automatic assignment"]
  },
  {
    slug: "association-labels",
    title: "HubSpot association labels: describe how records are related",
    excerpt: "How association labels work in HubSpot: where to see them in the Data Model Builder, single vs paired labels, the 50 label limit per object pair, cardinality, and where labels can be used.",
    type: "guide",
    problem: "How to",
    hubs: ["Smart CRM", "Sales Hub"],
    features: ["Associations"],
    tier: "Professional or Enterprise",
    permissions: "Super Admin to create labels",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 7,
    difficulty: "Intermediate",
    keywords: ["association labels", "associations", "data model", "primary company", "billing contact"]
  }
];

if (typeof module !== 'undefined') module.exports = ARTICLES;
if (typeof window !== 'undefined') window.ARTICLES = ARTICLES;
