/*
 * articles.js - index of every article. Source of truth for the homepage,
 * search, filters, related articles, sitemap, RSS, and llms.txt.
 *
 * Each entry needs a matching hand-written page at articles/<slug>/index.html
 * (copy article-template.html). Run `node tools/build.js` after editing.
 *
 * type:       'tip' (short) or 'guide' (step by step)
 * problem:    'Fix it' | 'How to' | 'Hidden trick' | 'Gotcha' | 'Developer'
 * hubs:       'Marketing Hub' | 'Sales Hub' | 'Service Hub' | 'Content Hub' | 'Data Hub' | 'Commerce Hub' | 'Smart CRM'
 * draft:      true keeps it out of every list, sitemap, feed, and llms.txt
 */
var ARTICLES = [
  {
    slug: 'workflow-wont-re-enroll',
    title: "Contact won't re-enroll in a HubSpot workflow? Check these 6 things",
    excerpt: 'HubSpot enrolls a record once by default. Why re-enrollment fails, how to turn it on, and the triggers that can never re-enroll.',
    type: 'guide',
    problem: 'Fix it',
    hubs: ['Marketing Hub', 'Sales Hub', 'Service Hub', 'Data Hub'],
    features: ['Workflows'],
    tier: 'Professional or Enterprise',
    permissions: 'Super Admin or Workflows',
    verified: '2026-10-02',
    published: '2026-10-02',
    minutes: 10,
    difficulty: 'Intermediate',
    keywords: ['re-enroll', 'reenroll', 're-enrollment', 'enrollment trigger', 'workflow not triggering', 'automation']
  },
  {
    slug: 'duplicates-after-import',
    title: 'HubSpot import created duplicate contacts? Why it happens and how to fix it',
    excerpt: 'HubSpot only matches imported rows by a unique identifier. Spot an import that duplicated records, clean it up, and stop it next time.',
    type: 'guide',
    problem: 'Fix it',
    hubs: ['Smart CRM', 'Data Hub', 'Marketing Hub', 'Sales Hub'],
    features: ['Imports', 'Data quality'],
    tier: 'Any tier (merging needs Professional)',
    permissions: 'Import access; Data quality tools to merge',
    verified: '2026-10-02',
    published: '2026-10-02',
    minutes: 15,
    difficulty: 'Intermediate',
    keywords: ['duplicate', 'duplicates', 'dedupe', 'deduplicate', 'merge', 'import', 'record id', 'email', 'company domain'],
    related: ['find-hubspot-portal-id']
  },
  {
    slug: 'coded-template-missing-from-picker',
    title: 'Your coded HubSpot template is missing from the template picker? Look under Other',
    excerpt: 'The page template picker opens on your active theme. Templates that are not part of a theme only appear under Other.',
    type: 'tip',
    problem: 'Gotcha',
    hubs: ['Content Hub'],
    features: ['Pages', 'Design Manager'],
    tier: 'Any tier with pages',
    permissions: 'Website or landing page access',
    verified: '2026-10-02',
    published: '2026-10-02',
    minutes: 3,
    difficulty: 'Beginner',
    keywords: ['template', 'coded template', 'template picker', 'select a template', 'theme', 'design manager', 'hubl', 'landing page', 'extends']
  },
  {
    slug: 'find-hubspot-portal-id',
    title: 'How to find your HubSpot portal ID (Hub ID)',
    excerpt: 'Your portal ID, also called Hub ID or account ID, is in the account menu and in every HubSpot URL.',
    type: 'tip',
    problem: 'How to',
    hubs: ['Smart CRM'],
    features: ['Settings'],
    tier: 'All tiers, including free',
    permissions: 'Any user',
    verified: '2026-10-02',
    published: '2026-10-02',
    minutes: 1,
    difficulty: 'Beginner',
    keywords: ['portal id', 'hub id', 'account id', 'portalid', 'hubid', 'account number', 'url']
  },
  {
    slug: "never-opened-email-stat",
    title: "HubSpot says 180,000 contacts never opened your email? Check who was ever sent one",
    excerpt: "A HubSpot segment of contacts who never opened an email also includes everyone who was never sent one. How to build the honest version before you sunset anyone.",
    type: "tip",
    problem: "Gotcha",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Segments", "Workflows"],
    tier: "Marketing Hub Professional for the workflow; segments on paid tiers",
    permissions: "Segments and Workflows access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Intermediate",
    keywords: ["never opened", "unengaged", "email sunset", "open rate", "segment"],
  },
  {
    slug: "speed-to-lead-sla-workflow",
    title: "Build a speed-to-lead workflow in HubSpot with a follow-up SLA and escalation",
    excerpt: "A HubSpot workflow that creates a call task when a lead arrives, checks whether anyone made contact after a day, and escalates by email to the owner if nobody did.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Marketing Hub"],
    features: ["Workflows"],
    tier: "Professional or Enterprise",
    permissions: "Super Admin or Workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 20,
    difficulty: "Intermediate",
    keywords: ["speed to lead", "sla", "lead response", "task", "escalation"],
  },
  {
    slug: "sql-count-zero",
    title: "Your HubSpot report shows zero SQLs? Set lifecycle stage from the deal, not the contact",
    excerpt: "If reps work deals and never touch the contact's lifecycle stage, SQL reports stay at zero. A workflow can set associated contacts to Sales Qualified Lead when a deal reaches the right stage.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Sales Hub", "Marketing Hub"],
    features: ["Workflows", "Lifecycle stages"],
    tier: "Professional or Enterprise",
    permissions: "Super Admin or Workflows",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Intermediate",
    keywords: ["sql", "sales qualified lead", "lifecycle stage", "report zero"],
  },
  {
    slug: "troubleshoot-enrollment",
    title: "Why didn't this record enroll? Use HubSpot's Troubleshoot enrollment tool",
    excerpt: "HubSpot workflows have a built-in tool that tests a specific record against the nine enrollment checks and tells you why it did or did not enroll.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Marketing Hub", "Sales Hub", "Service Hub", "Data Hub"],
    features: ["Workflows"],
    tier: "Professional or Enterprise",
    permissions: "Access to view the workflow",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Beginner",
    keywords: ["why not enrolled", "enrollment history", "workflow not triggering"],
  },
  {
    slug: "enrich-records-record-id-import",
    title: "Enrich HubSpot companies from a spreadsheet when names don't match: import by Record ID",
    excerpt: "When company names in a spreadsheet match more than one HubSpot company, export Record IDs, match your data to them, and import with Record ID as the identifier.",
    type: "guide",
    problem: "How to",
    hubs: ["Smart CRM", "Data Hub"],
    features: ["Imports", "Properties"],
    tier: "Any tier (property creation needs property settings access)",
    permissions: "Import access and Edit property settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 25,
    difficulty: "Intermediate",
    keywords: ["record id", "import update", "enrich", "naics"],
  },
  {
    slug: "bulk-assign-owners-from-sheet",
    title: "Bulk assign HubSpot company owners from a spreadsheet without overwriting anyone",
    excerpt: "Use a customer's own file of account owners to set Company owner on thousands of HubSpot companies, only where none is set, and handle owners who are not HubSpot users.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Smart CRM"],
    features: ["Imports", "Companies"],
    tier: "Any tier",
    permissions: "Import access; bulk edit access to companies",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 20,
    difficulty: "Intermediate",
    keywords: ["company owner", "assign owners", "bulk owner"],
  },
  {
    slug: "opt-out-contact-all-email",
    title: "How to opt a HubSpot contact out of all email (and why the API can't do it)",
    excerpt: "Actions, Opt out of email stops future marketing and one-to-one email from HubSpot. Where it lives, what it does not stop, and why scripts and the API cannot set it.",
    type: "tip",
    problem: "How to",
    hubs: ["Marketing Hub", "Sales Hub", "Smart CRM"],
    features: ["Contacts", "Email"],
    tier: "All tiers",
    permissions: "Marketing access permissions",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 4,
    difficulty: "Beginner",
    keywords: ["unsubscribe", "opt out", "gdpr", "do not email"],
  },
  {
    slug: "api-scripts-create-duplicates",
    title: "Your script created duplicate HubSpot records? Merge them, don't delete them",
    excerpt: "Why bulk writes through the HubSpot API create duplicate companies and contacts, how to merge instead of delete to keep associations, and how to write the script so it does not happen again.",
    type: "guide",
    problem: "Developer",
    hubs: ["Smart CRM"],
    features: ["API", "Duplicates"],
    tier: "Any tier with a private app",
    permissions: "Private app with CRM write scopes",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Advanced",
    keywords: ["api", "merge", "duplicates", "upsert"],
  },
  {
    slug: "template-doesnt-allow-modules",
    title: "'This template doesn't allow modules to be added' in HubSpot: three causes",
    excerpt: "A blank HubSpot page that will not let you add modules usually has a template problem: an empty drag and drop area, a broken extends path, or overlapping columns.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Content Hub"],
    features: ["Pages", "Design Manager"],
    tier: "Any tier with website or landing pages",
    permissions: "Design Manager and page access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Advanced",
    keywords: ["dnd_area", "template", "editor error", "modules"],
  },
  {
    slug: "clone-landing-page-per-location",
    title: "Clone a HubSpot landing page for each location: what to change every time",
    excerpt: "How to clone one good HubSpot landing page for each community or location, and the four settings plus content to change on every clone.",
    type: "guide",
    problem: "How to",
    hubs: ["Content Hub"],
    features: ["Pages"],
    tier: "Any tier with website or landing pages",
    permissions: "Create and edit pages",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Beginner",
    keywords: ["clone page", "landing page", "location pages"],
  },
  {
    slug: "starter-page-limit",
    title: "'You have reached your page limit' in HubSpot: look at your drafts",
    excerpt: "HubSpot's Starter tier limits how many landing pages you can create. Untitled drafts show up in the same list as live pages, so check them first.",
    type: "tip",
    problem: "Gotcha",
    hubs: ["Content Hub"],
    features: ["Pages"],
    tier: "Starter tier",
    permissions: "Page access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 4,
    difficulty: "Beginner",
    keywords: ["page limit", "starter", "untitled drafts"],
  },
  {
    slug: "offline-sources-explained",
    title: "HubSpot 'Offline Sources' is not offline: how to see what created those contacts",
    excerpt: "Offline Sources in HubSpot means a record was created outside tracked web traffic, such as an import, the API, a connected app, or by hand. How to break it apart with the drill-down properties.",
    type: "guide",
    problem: "Hidden trick",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Properties", "Attribution"],
    tier: "All tiers for the properties; reports need Professional",
    permissions: "Any user who can view contacts",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 12,
    difficulty: "Intermediate",
    keywords: ["offline sources", "original source", "attribution", "drill-down"],
  },
  {
    slug: "campaign-zero-sessions",
    title: "HubSpot campaign shows lots of influenced contacts but 0 sessions? You need tracking URLs",
    excerpt: "A HubSpot campaign full of assets can show hundreds of influenced contacts and zero sessions. Sessions only count when visits arrive through the campaign's tracking URL.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Marketing Hub"],
    features: ["Campaigns"],
    tier: "Marketing Hub Professional or Enterprise",
    permissions: "Campaigns access and Tracking URLs access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Intermediate",
    keywords: ["campaign sessions", "utm", "tracking url", "influenced contacts"],
  },
  {
    slug: "which-reports-hubspot-can-build",
    title: "Which reports can HubSpot build? Report types, limits, and what needs a higher tier",
    excerpt: "HubSpot's custom report types: single object, funnel, custom report builder, attribution, and email reports. What each can and cannot do, and which tier you need.",
    type: "guide",
    problem: "How to",
    hubs: ["Smart CRM", "Marketing Hub", "Sales Hub"],
    features: ["Reports"],
    tier: "Custom reports need Professional or Enterprise",
    permissions: "Create and own, and Edit reports",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Beginner",
    keywords: ["custom report", "report builder", "report types", "funnel"],
  },
  {
    slug: "hubsql-beta-api",
    title: "HubSQL beta: what it is, what it is not, and the 403 MISSING_SCOPES fix",
    excerpt: "HubSpot's HubSQL beta lets you run SQL against CRM data over an API. What it can do, why it cannot connect to your SQL server, and how to fix a 403 for missing scopes.",
    type: "tip",
    problem: "Developer",
    hubs: ["Smart CRM"],
    features: ["API"],
    tier: "Private beta (invite only at the time of writing)",
    permissions: "Private or legacy app with the required read scopes",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Advanced",
    keywords: ["hubsql", "sql", "api", "403", "missing scopes"],
  },
  {
    slug: "speed-up-landing-page",
    title: "Speed up a HubSpot landing page: measure first, then fix images and page-level code",
    excerpt: "How to find out why a HubSpot landing page is slow with Lighthouse, then fix the usual causes: heavy images, layout shift, and extra scripts in the page's Head and Footer HTML.",
    type: "guide",
    problem: "How to",
    hubs: ["Content Hub"],
    features: ["Pages", "Performance"],
    tier: "Any tier with landing or website pages",
    permissions: "Edit pages",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Intermediate",
    keywords: ["page speed", "lighthouse", "core web vitals", "head html"],
  },
  {
    slug: "default-lifecycle-and-deal-stages",
    title: "HubSpot's default lifecycle stages, lead statuses, and deal stages (with internal names)",
    excerpt: "The out-of-the-box HubSpot lifecycle stages, lead statuses, and default Sales Pipeline deal stages, with the internal values you need for imports, workflows, and APIs.",
    type: "tip",
    problem: "How to",
    hubs: ["Smart CRM", "Sales Hub"],
    features: ["Properties", "Deals"],
    tier: "All tiers (editing stages needs Professional for some objects)",
    permissions: "Any user can view; Edit property settings to change",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["lifecycle stages", "lead status", "deal stages", "internal names", "default pipeline"]
  },
  {
    slug: "lifecycle-date-properties",
    title: "Stop creating custom timestamp fields: HubSpot already tracks when a record entered each lifecycle stage",
    excerpt: "HubSpot automatically creates date entered and time in stage properties for every lifecycle stage. Check them before you build custom date fields for a journey or funnel.",
    type: "tip",
    problem: "Hidden trick",
    hubs: ["Smart CRM", "Marketing Hub", "Sales Hub"],
    features: ["Properties", "Lifecycle stages"],
    tier: "All tiers for the properties; reports and workflows depend on your tier",
    permissions: "Any user can view; reports need report access",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 6,
    difficulty: "Intermediate",
    keywords: ["date entered", "time in stage", "lifecycle timestamps", "became a"]
  },
  {
    slug: "detect-hubspot-tracking-code",
    title: "How to tell if a website uses HubSpot: check for the tracking code",
    excerpt: "HubSpot's tracking code is a script from js.hs-scripts.com with the account's Hub ID. How to check one site by hand, validate your own, and scan a list of domains.",
    type: "guide",
    problem: "How to",
    hubs: ["Smart CRM", "Marketing Hub"],
    features: ["Tracking code"],
    tier: "All tiers",
    permissions: "Settings access to see your own tracking code",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 12,
    difficulty: "Intermediate",
    keywords: ["tracking code", "hs-scripts", "hub id", "uses hubspot", "validate"]
  },
  {
    slug: "close-stale-deals",
    title: "How to close out stale HubSpot deals safely: check activity first, then use a reason",
    excerpt: "A safe routine for closing old HubSpot deals: find stale ones on the board, check last activity and next steps, then move them to Closed Lost with a reason.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub"],
    features: ["Deals"],
    tier: "All tiers (bulk edit and reports vary)",
    permissions: "Edit access to deals",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 10,
    difficulty: "Beginner",
    keywords: ["stale deals", "closed lost", "pipeline cleanup", "last activity"]
  },
  {
    slug: "duplicate-companies-from-connector-ids",
    title: "Two HubSpot companies share one connector ID? Merge the safe ones and hold the collisions",
    excerpt: "When a sync connector keys on an external ID and two HubSpot companies carry it, data splits across both. How to triage the groups, merge the safe ones, and leave genuine ID collisions alone.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Smart CRM", "Data Hub"],
    features: ["Duplicates", "Integrations"],
    tier: "Any tier (bulk merge tooling varies; API merge needs a private app)",
    permissions: "Super Admin or merge access to companies",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 30,
    difficulty: "Advanced",
    keywords: ["connectwise", "duplicate companies", "merge", "connector id", "sync"]
  },
  {
    slug: "callrail-duplicate-contacts",
    title: "Call tracking is creating duplicate HubSpot contacts? Fix the source before you merge",
    excerpt: "Placeholder emails from a call tracking tool stop texts and calls matching real HubSpot contacts and create duplicates. How to analyze the duplicates by phone, what is safe to merge, and how to stop it.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Smart CRM", "Marketing Hub"],
    features: ["Duplicates", "Integrations"],
    tier: "Any tier (workflow-based dedupe needs Data Hub Professional)",
    permissions: "Merge access to contacts; settings access in the call tracking tool",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 25,
    difficulty: "Advanced",
    keywords: ["callrail", "duplicate contacts", "placeholder email", "texting", "call tracking"]
  },
  {
    slug: "theme-upload-validation-errors",
    title: "Seven HubSpot theme upload errors I hit, and how to sweep for the whole class",
    excerpt: "Building a HubSpot theme from scratch failed validation six times. The seven errors: reserved field names, template type suffixes, global field IDs, unsupported field types, and breakpoint names.",
    type: "guide",
    problem: "Developer",
    hubs: ["Content Hub"],
    features: ["Design Manager", "Themes"],
    tier: "Any account with CMS or Content Hub access",
    permissions: "Developer access and CLI access to the account",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Advanced",
    keywords: ["theme upload", "validation", "fields.json", "reserved field name", "hs cms upload"]
  },
  {
    slug: "exclude-own-traffic",
    title: "Exclude your own visits from HubSpot analytics (and the catch with form tests)",
    excerpt: "How to keep your own traffic out of HubSpot analytics with an IP filter and referrer filter, what bot filtering does, and what happens to your own test form submissions.",
    type: "tip",
    problem: "How to",
    hubs: ["Marketing Hub", "Smart CRM"],
    features: ["Tracking code", "Analytics"],
    tier: "All tiers",
    permissions: "Account access to Tracking & Analytics settings",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Beginner",
    keywords: ["exclude traffic", "internal traffic", "ip filter", "analytics"]
  },
  {
    slug: "teams-phone-recordings-to-hubspot",
    title: "Can HubSpot get Microsoft Teams Phone recordings and transcripts? What works and what doesn't",
    excerpt: "HubSpot logs Teams calls and syncs Teams meeting recordings, but not Teams Phone recordings. What Microsoft Graph offers, the 2026 transcript setting, HubSpot's transcripts API, and a Make versus Data Hub comparison.",
    type: "guide",
    problem: "Developer",
    hubs: ["Sales Hub", "Data Hub"],
    features: ["Integrations", "Calling"],
    tier: "See the HubSpot Teams app page for requirements; the custom pipeline needs a public app",
    permissions: "HubSpot Super Admin; Microsoft 365 admin",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 15,
    difficulty: "Advanced",
    keywords: ["microsoft teams", "teams phone", "call transcripts", "recordings", "microsoft graph"]
  },
  {
    slug: "hubspot-object-type-ids",
    title: "HubSpot object type IDs (0-1, 0-47, 0-48) and how to use them in links and the API",
    excerpt: "The numeric object type IDs behind HubSpot URLs and API calls: contacts 0-1, companies 0-2, deals 0-3, meetings 0-47, calls 0-48 and more, with a fix for links that land on a blank page.",
    type: "tip",
    problem: "Hidden trick",
    hubs: ["Smart CRM"],
    features: ["API", "Links"],
    tier: "All tiers",
    permissions: "Any user",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 5,
    difficulty: "Intermediate",
    keywords: ["object type id", "0-47", "0-48", "objecttypeid", "meeting link", "blank page"]
  },
  {
    slug: "revenue-attribution-deal-requirements",
    title: "Deal missing from HubSpot revenue attribution? A deal needs four things",
    excerpt: "HubSpot's revenue attribution reports only include closed won deals with an associated contact, known amount, create date and close date, and recorded interactions. A checklist for why a deal is missing.",
    type: "guide",
    problem: "Fix it",
    hubs: ["Marketing Hub", "Sales Hub"],
    features: ["Attribution", "Campaigns"],
    tier: "Revenue attribution reports need Marketing Hub Enterprise",
    permissions: "Report access; edit access to deals to fix records",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 8,
    difficulty: "Intermediate",
    keywords: ["revenue attribution", "campaign revenue", "closed won", "deal missing"]
  },
  {
    slug: "spreadsheet-board-to-hubspot-pipelines",
    title: "Move a project board (Planner, Trello, a spreadsheet) into HubSpot pipelines",
    excerpt: "How to turn an exported task board into HubSpot pipelines, deals, companies, contacts, and notes: map each field, do a dry run, approve each piece, and verify counts.",
    type: "guide",
    problem: "How to",
    hubs: ["Sales Hub", "Smart CRM"],
    features: ["Pipelines", "Imports"],
    tier: "The number of pipelines depends on your subscription",
    permissions: "Super Admin or access to create pipelines and properties",
    verified: "2026-10-03",
    published: "2026-10-03",
    minutes: 40,
    difficulty: "Advanced",
    keywords: ["planner", "trello", "board import", "pipelines", "migrate"]
  }
];

if (typeof module !== 'undefined') module.exports = ARTICLES;
if (typeof window !== 'undefined') window.ARTICLES = ARTICLES;
